--BMW Master Cart Model
insert into `premium-car`.car_model (car_model_id, car_maker, car_type, model_name)
values (1,'BMW','SEDAN','3 Series'),
(2,'BMW','SEDAN','5 Series'),
(3,'BMW','SEDAN','7 Series'),
(4,'BMW','COUPE','8 Series'),
(5,'BMW','SUV','X1'),
(6,'BMW','SUV','X3'),
(7,'BMW','COUPE','X4'),
(8,'BMW','SUV','X5'),
(9,'BMW','COUPE','X6'),
(10,'BMW','SUV','X7'),
(11,'BMW','SEDAN','3 Series Gran Turismo'),
(12,'BMW','SEDAN','6 Series Gran Turismo'),
(13,'BMW','SEDAN','M2 Competition'),
(14,'BMW','Convertible','Z4 M40i'),
(15,'BMW','SEDAN','M5 Competition')



--Master Varient inserts
insert into `premium-car`.varient (varient_id, fuel_type, transmission_type, varient_name, car_model_car_model_id)
values (1, 'Diesel', 'Auto', '320d Sport', 1),
(2, 'Diesel', 'Automatic', '320d Luxury Line', 1),
(3, 'Petrol', 'Automatic', '330i M Sport', 1),
(4, 'Petrol', 'Automatic', '530i M Sport', 2),
(5, 'Diesel', 'Automatic', '520d Luxury Line', 2),
(6, 'Diesel', 'Automatic', '530d M Sport', 2),
(7, 'Diesel', 'Automatic', '730Ld DPE', 3),
(8, 'Diesel', 'Automatic', '730Ld DPE Signature', 3),
(9, 'Diesel', 'Automatic', '730Ld M Sport', 3),
(10, 'Petrol', 'Automatic', '730Li DPE Signature', 3),
(11, 'Petrol', 'Automatic', '745Le xDrive', 3),
(12, 'Petrol', 'Automatic', 'M760Li xDrive', 3),
(13, 'Diesel', 'Automatic', 'X1 sDrive20d Expedition', 5),
(14, 'Diesel', 'Automatic', 'X1 sDrive20d xLine', 5),
(15, 'Diesel', 'Automatic', 'X1 sDrive20d M Sport', 5),
(16, 'Diesel', 'Automatic', 'X1 xDrive20d M Sport', 5),
(17, 'Petrol', 'Automatic', 'X1 sDrive20i xLine', 5),
(18, 'Diesel', 'Automatic', 'X1 xDrive20d M Sport', 5),
(19, 'Petrol', 'Automatic', 'X3 xDrive30i Luxry Line', 6),
(20, 'Diesel', 'Automatic', 'X3 xDrive20d xLine', 6),
(21, 'Diesel', 'Automatic', 'X3 xDrive20d Luxury Line', 6),
(22, 'Diesel', 'Automatic ', 'X4 xDrive20d M Sport X', 7),
(23, 'Diesel', 'Automatic', 'X4 xDrive30d M Sport X', 7),
(24, 'Petrol', 'Automatic', 'X4 xDrive30i M Sport X', 7),
(25, 'Diesel', 'Automatic', 'X5 xDrive30d Sport', 8),
(26, 'Diesel', 'Automatic', 'X5 xDrive30d xLine', 8),
(27, 'Petrol', 'Automatic', 'X5 xDrive40i M Sport', 8),
(28, 'Diesel', 'Automatic', 'X7 xDrive30d DPE', 10),
(29, 'Diesel', 'Automatic', 'X7 xDrive30d DPE Signature', 10),
(30, 'Petrol', 'Automatic', 'X7 xDrive40i M Sport', 10),
(31, 'Diesel', 'Automatic', '320d GT Sport', 11),
(32, 'Diesel', 'Automatic', '320d GT Luxury Line', 11),
(33, 'Petrol', 'Automatic', '330i GT M Sport', 11),
(34, 'Diesel', 'Automatic', '620d Luxury Line', 12),
(35, 'Diesel', 'Automatic', '630d M Sport', 12),
(36, 'Petrol', 'Automatic', '630i Luxury Line', 12),
(37, 'Petrol', 'Manual', 'M2 Competition', 13),
(38, 'Petrol', 'Manual', 'Z4 sDrive20i', 14),
(39, 'Petrol', 'Manual', 'Z4 M40i', 14),
(40, 'Petrol', 'Manual', 'M5 Competition', 15)

